language: c

compiler:
    - gcc

git:
    depth: 1

matrix:
  include:
     - os: linux
       addons:
          apt:
               sources:
                    - ubuntu-toolchain-r-test
               packages:
                    - g++-7
           env:
                - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir glibc-build
    - cd glibc-build
    - ../glibc/configure --prefix=/usr
    - make -j $(nproc)
