language: c

compiler:
    - gcc

git:
    depth: 1

before_install:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

script:
    - mkdir glibc-build
    - cd glibc-build
    - ../glibc/configure --prefix=/usr
    - make -j $(nproc)
